### ISSUE TITLE
Saker att inte glömma

### ISSUE THREAD

**Issue by optimusprime94** [optimusprime94/CodebustersAppWMU3#1]
- Background task
- Notifikationer **om man är nära**

- Felkontroller behöver implementeras

**Comment by Mackan95bowling** [comment]
Vi ska spara allt i XML fil enligt vad Johannes sa på handledningen

**Comment by optimusprime94** [comment]
Blev en databas istället :)

**Comment by optimusprime94** [comment]
Det verkar gå spara information nu, det vi behöver göra är: 

- Background task
- Kunna öppna och spara bilder
- Notifikationer om man är nära
- kunna använda befintliga bilder
- m.m

**Comment by optimusprime94** [comment]
Tillbaka knappen fungerar inte som den ska...den stackar sidorna så man går inte alltid dit man vill utan förra sidan man va på

**Comment by optimusprime94** [comment]
Nu verkar det bara vara Background task och Notifikationer
